# Games Sales Data Analytics

In [ ]:
import pandas as pd

In [ ]:
games = pd.read_csv('Games Sales - Games.csv')
games.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 177 entries, 0 to 176
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       177 non-null    object
 1   Sales      177 non-null    float64
 2   Series     141 non-null    object
 3   Release    177 non-null    object
 4   Genre      177 non-null    object
 5   Developer  177 non-null    object
 6   Publisher  177 non-null    object
dtypes: float64(1), object(6)
memory usage: 9.8+ KB

In [ ]:
games.head()

,Name,Sales,Series,Release,Genre,Developer,Publisher
0,PlayerUnknown's Battlegrounds,42.0,NaN,12/1/2017,Battle royale,PUBG Studios,Krafton
1,Minecraft,33.0,Minecraft,11/1/2011,"Sandbox, survival",Mojang Studios,Mojang Studios
2,Diablo III,20.0,Diablo,5/1/2012,Action role-playing,Blizzard Entertainment,Blizzard Entertainment
3,Garry's Mod,20.0,NaN,11/1/2006,Sandbox,Facepunch Studios,Valve
4,Terraria,17.2,NaN,5/1/2011,Action-adventure,Re-Logic,Re-Logic

In [ ]:
games['Release'] = pd.to_datetime(games['Release'])
games.head()

,Name,Sales,Series,Release,Genre,Developer,Publisher
0,PlayerUnknown's Battlegrounds,42.0,NaN,2017-12-01,Battle royale,PUBG Studios,Krafton
1,Minecraft,33.0,Minecraft,2011-11-01,"Sandbox, survival",Mojang Studios,Mojang Studios
2,Diablo III,20.0,Diablo,2012-05-01,Action role-playing,Blizzard Entertainment,Blizzard Entertainment
3,Garry's Mod,20.0,NaN,2006-11-01,Sandbox,Facepunch Studios,Valve
4,Terraria,17.2,NaN,2011-05-01,Action-adventure,Re-Logic,Re-Logic

In [33]:
release = games[['Name', 'Release']]
release.head()

                            Name    Release
0  PlayerUnknown's Battlegrounds 2017-12-01
1                      Minecraft 2011-11-01
2                     Diablo III 2012-05-01
3                    Garry's Mod 2006-11-01
4                       Terraria 2011-05-01

Which game is the oldest?

In [38]:
oldest_games = release.sort_values(by=['Release'])
oldest_games.head()

                                       Name    Release
133                                 Hydlide 1984-12-01
34   Where in the World Is Carmen Sandiego? 1985-06-01
88                     International Karate 1985-11-01
162                                  Tetris 1988-01-01
22                             Last Ninja 2 1988-08-01

Which game is the newest?

In [37]:
newest_games = release.sort_values(by=['Release'], ascending=False)
newest_games.head()

                   Name    Release
20              Valheim 2021-02-01
27       Cyberpunk 2077 2020-12-01
110  Crusader Kings III 2020-09-01
10            Fall Guys 2020-08-01
139             Mordhau 2019-04-01

Which publisher published most of the games?

In [ ]:
games.value_counts('Publisher')

Publisher
Electronic Arts           19
Blizzard Entertainment    10
Paradox Interactive        7
Activision                 6
GT Interactive             5
                          ..
Frontier Developments      1
Facepunch Studios          1
FX Interactive             1
Epyx                       1
id Software                1
Length: 96, dtype: int64

Which developer developed most of the games?

In [ ]:
games.value_counts('Developer')

Developer
Blizzard Entertainment        10
Maxis                          6
Paradox Development Studio     5
id Software                    4
Westwood Studios               4
                              ..
Introversion Software          1
Infocom                        1
Heuristic Park                 1
Gray Matter Interactive        1
Kojima Productions             1
Length: 109, dtype: int64

In [ ]:
series = games[['Series', 'Name', 'Sales']].dropna()
series.head()

        Series                      Name  Sales
1    Minecraft                 Minecraft   33.0
2       Diablo                Diablo III   20.0
5     Warcraft         World of Warcraft   14.0
6    Half-Life               Half-Life 2   12.0
7  The Witcher  The Witcher 3: Wild Hunt   12.0

Which series have the most sales?

In [ ]:
most_sales_by_series = series.groupby('Series').sum()
most_sales_by_series.sort_values(by=['Sales'], ascending=False).head()

           Sales
Series
Minecraft   33.0
Diablo      26.0
The Sims    24.0
Half-Life   21.0
StarCraft   21.0

Which series have the most games?

In [ ]:
series.value_counts('Series')

Series
StarCraft               6
Command & Conquer       5
Age of Empires          4
Civilization            4
Dark Souls              3
                       ..
International Karate    1
Hydlide                 1
Hearts of Iron          1
Harry Potter            1
Zork                    1
Length: 91, dtype: int64